### ISSUE TITLE
WatchEvent.context() may be null

### ISSUE THREAD

**Issue by raboof** [sbt/io#112]
While watching I sometimes see:
```
[error] Error occurred obtaining files to watch.  Terminating continuous execution...
[error] java.lang.NullPointerException
[error] 	at sun.nio.fs.UnixPath.toUnixPath(UnixPath.java:198)
[error] 	at sun.nio.fs.UnixPath.resolve(UnixPath.java:397)
[error] 	at sun.nio.fs.UnixPath.resolve(UnixPath.java:43)
[error] 	at sbt.internal.io.SourceModificationWatch$.expandEvent(SourceModificationWatch.scala:70)
[error] 	at sbt.internal.io.SourceModificationWatch$.$anonfun$watch$1(SourceModificationWatch.scala:
28)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error] 	at scala.collection.immutable.List.map(List.scala:295)
[error] 	at sbt.internal.io.SourceModificationWatch$.watch(SourceModificationWatch.scala:28)
[error] 	at sbt.Watched$.liftedTree1$1(Watched.scala:106)
[error] 	at sbt.Watched$.executeContinuously(Watched.scala:104)
[error] 	at sbt.BasicCommands$.$anonfun$continuous$2(BasicCommands.scala:231)
[error] 	at sbt.CommandUtil$.withAttribute(CommandUtil.scala:49)
[error] 	at sbt.BasicCommands$.$anonfun$continuous$1(BasicCommands.scala:229)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:134)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:153)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:242)
```

It seems indeed `WatchEvent.context()` may be null (https://docs.oracle.com/javase/7/docs/api/java/nio/file/WatchEvent.html), and I suspect `UnixPath.resolve` does not accept `null`.

**Comment by felher** [comment]
This is very annoying to me, but I have neither the knowledge nor the time to look into it. I'm willing to spend 50 bucks to help fix this issue and improve SBT. So if anyone wants to take a shot at it: https://www.bountysource.com/issues/53003420-watchevent-context-may-be-null

**Comment by dwijnand** [comment]
@felher nice! I've added the "help wanted" label to draw attention to it.

**Comment by eed3si9n** [comment]
Not sure if it's related but there's https://github.com/sbt/io/pull/138 and https://github.com/sbt/sbt/pull/4052 for macOS.

**Comment by dwijnand** [comment]
fixed in https://github.com/sbt/io/pull/140, which is due in sbt/io 1.1.7 and probably sbt 1.1.4.

**Comment by felher** [comment]
Great. Can I already test hat? Did it make it into 1.1.4? :)

**Comment by dwijnand** [comment]
no sorry sbt/io 1.1.7 wasn't updated in sbt 1.1.4, so this will be either sbt 1.1.5 or sbt 1.2.0.
