### ISSUE TITLE
FileTreeView#list throws IllegalStateException via Retry

### ISSUE THREAD

**Issue by eed3si9n** [sbt/io#293]
## steps

I'm not sure what the repro steps are here but I'm seeing AppVeyor fail for  https://github.com/sbt/sbt/pull/5517 which brings in the latest into sbt/sbt.

## problem

<details>
<summary>

```scala
[error] 20/05/02 03:10:48 INFO ShutdownHookManager: Shutdown hook called
[error] 20/05/02 03:10:48 INFO ShutdownHookManager: Deleting directory C:\Users\appveyor\AppData\Local\Temp\1\spark-6dd02d89-1aa5-468c-81e3-f2b9a6331370
[error] java.lang.IllegalStateException
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:45)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] 	at sbt.internal.nio.SwovalFileTreeView$.list(SwovalConverters.scala:57)
[error] 	at sbt.nio.file.FileTreeView$$anon$1.listPath(FileTreeView.scala:331)
[error] 	at sbt.nio.file.FileTreeView$$anon$1.fillBuffer(FileTreeView.scala:378)
[error] 	at sbt.nio.file.FileTreeView$$anon$1.next(FileTreeView.scala:391)
[error] 	at sbt.nio.file.FileTreeView$$anon$1.next(FileTreeView.scala:322)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at sbt.nio.file.FileTreeView$$anon$1.foreach(FileTreeView.scala:322)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
[error] 	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:662)
[error] 	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:639)
[error] 	at scala.collection.TraversableOnce.to(TraversableOnce.scala:348)
[error] 	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:346)
[error] 	at sbt.nio.file.FileTreeView$$anon$1.to(FileTreeView.scala:322)
[error] 	at scala.collection.TraversableOnce.toVector(TraversableOnce.scala:344)
[error] 	at scala.collection.TraversableOnce.toVector$(TraversableOnce.scala:344)
[error] 	at sbt.nio.file.FileTreeView$$anon$1.toVector(FileTreeView.scala:322)
[error] 	at sbt.nio.file.FileTreeView$.all(FileTreeView.scala:272)
[error] 	at sbt.nio.file.FileTreeView$Ops$.list$extension1(FileTreeView.scala:100)
[error] 	at sbt.scriptedtest.ScriptedTests.$anonfun$runBatchedTests$1(ScriptedTests.scala:282)
```

</summary>

```scala
[error] 20/05/02 03:10:48 INFO ShutdownHookManager: Shutdown hook called
[error] 20/05/02 03:10:48 INFO ShutdownHookManager: Deleting directory C:\Users\appveyor\AppData\Local\Temp\1\spark-36c19c77-be0e-4f32-bb2d-3506baa21d3b
[error] 20/05/02 03:10:48 INFO ShutdownHookManager: Shutdown hook called
[error] 20/05/02 03:10:48 INFO ShutdownHookManager: Deleting directory C:\Users\appveyor\AppData\Local\Temp\1\spark-4a8b15b4-314b-4e42-ad46-86ad4e6d4486
[error] 20/05/02 03:10:48 INFO ShutdownHookManager: Shutdown hook called
[error] 20/05/02 03:10:48 INFO ShutdownHookManager: Deleting directory C:\Users\appveyor\AppData\Local\Temp\1\spark-6dd02d89-1aa5-468c-81e3-f2b9a6331370
[error] java.lang.IllegalStateException
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:45)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] 	at sbt.internal.nio.SwovalFileTreeView$.list(SwovalConverters.scala:57)
[error] 	at sbt.nio.file.FileTreeView$$anon$1.listPath(FileTreeView.scala:331)
[error] 	at sbt.nio.file.FileTreeView$$anon$1.fillBuffer(FileTreeView.scala:378)
[error] 	at sbt.nio.file.FileTreeView$$anon$1.next(FileTreeView.scala:391)
[error] 	at sbt.nio.file.FileTreeView$$anon$1.next(FileTreeView.scala:322)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at sbt.nio.file.FileTreeView$$anon$1.foreach(FileTreeView.scala:322)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
[error] 	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:662)
[error] 	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:639)
[error] 	at scala.collection.TraversableOnce.to(TraversableOnce.scala:348)
[error] 	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:346)
[error] 	at sbt.nio.file.FileTreeView$$anon$1.to(FileTreeView.scala:322)
[error] 	at scala.collection.TraversableOnce.toVector(TraversableOnce.scala:344)
[error] 	at scala.collection.TraversableOnce.toVector$(TraversableOnce.scala:344)
[error] 	at sbt.nio.file.FileTreeView$$anon$1.toVector(FileTreeView.scala:322)
[error] 	at sbt.nio.file.FileTreeView$.all(FileTreeView.scala:272)
[error] 	at sbt.nio.file.FileTreeView$Ops$.list$extension1(FileTreeView.scala:100)
[error] 	at sbt.scriptedtest.ScriptedTests.$anonfun$runBatchedTests$1(ScriptedTests.scala:282)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
[error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.scriptedtest.ScriptedTests.runBatchTests$1(ScriptedTests.scala:240)
[error] 	at sbt.scriptedtest.ScriptedTests.runBatchedTests(ScriptedTests.scala:291)
[error] 	at sbt.scriptedtest.ScriptedTests.$anonfun$batchScriptedRunner$10(ScriptedTests.scala:148)
[error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:490)
[error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:500)
[error] 	at sbt.scriptedtest.ScriptedTests.$anonfun$batchScriptedRunner$9(ScriptedTests.scala:148)
[error] 	at sbt.scriptedtest.ScriptedRunner.$anonfun$runAll$1(ScriptedTests.scala:467)
[error] 	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.flatmap2combiner(ParArray.scala:419)
[error] 	at scala.collection.parallel.ParIterableLike$FlatMap.leaf(ParIterableLike.scala:1074)
[error] 	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
[error] 	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
[error] 	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
[error] 	at scala.collection.parallel.ParIterableLike$FlatMap.tryLeaf(ParIterableLike.scala:1070)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:153)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error] 	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
[error] 	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
[error] 	at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:379)
[error] 	at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:379)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:440)
[error] 	at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult(Tasks.scala:423)
[error] 	at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult$(Tasks.scala:416)
[error] 	at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:60)
[error] 	at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:960)
[error] 	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
[error] 	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
[error] 	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
[error] 	at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:955)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:153)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error] 	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] (scripted) java.lang.IllegalStateException
[error] Total time: 579 s (09:39), completed May 2, 2020 3:10:51 AM

```

</details>

## expectation

Try not to throw?

## note

@retronym added some optimization to `Retry` in https://github.com/sbt/io/pull/291 recently, but I'm not sure if there is a problem with the code change, or it just ended up exposing some other logical error.

Scripted test tries to call this at the end:

```scala
          val view = sbt.nio.file.FileTreeView.default
          val base = tempTestDir.getCanonicalFile.toGlob
          val global = base / "global"
          val globalLogging = base / ** / "global-logging"
          def recursiveFilter(glob: Glob): PathFilter = (glob: PathFilter) || glob / **
          val keep: PathFilter = recursiveFilter(global) || recursiveFilter(globalLogging)
          val toDelete = view.list(base / **, !keep).map(_._1).sorted.reverse
```

while the traversal is happening (?), the log shows that directories are being deleted by a shutdown hook.

**Comment by retronym** [comment]
Maybe `var attempt = 0` is what the correct initial value after my refactoring to `Retry`, although that alone would not explain a logic error when the retry limit is default:

```
private[sbt] object Retry {
  private lazy val limit = {
    val defaultLimit = 10
    try System.getProperty("sbt.io.retry.limit", defaultLimit.toString).toInt
    catch { case NonFatal(_) => defaultLimit }
```

**Comment by retronym** [comment]
I see the off-by-one error now, will submit a fix shortly.
